output "ak_security_audit_stack_id" {
  description = "Stack identifier for the AccuKnox security auditor deployment."
  value       = aws_cloudformation_stack.ak_security_audit.id
}

output "ak_security_audit_role_arn" {
  description = "Management account role ARN generated by the CloudFormation stack."
  value       = local.accuknox_role_arn
}

output "accuknox_api_request" {
  description = "Structured AccuKnox onboarding API request details."
  value = {
    method  = "POST"
    url     = local.accuknox_request_url
    headers = local.accuknox_request_headers
    body    = local.accuknox_request_body
  }
  sensitive = true
}


output "accuknox_onboarding_status" {
  description = "Status of the AccuKnox onboarding API call."
  value       = var.accuknox_api_token != "" ? "AccuKnox onboarding executed via terracurl - check response below" : "No API token provided - onboarding skipped"
  sensitive   = false
}

output "accuknox_onboarding_response" {
  description = "Response from the AccuKnox onboarding API call."
  value       = var.accuknox_api_token != "" ? try(data.terracurl_request.accuknox_onboarding[0].response, "No response available") : "No API token provided"
  sensitive   = true
}
